version: '3.5'
services:
    #`The App`
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: web-vsi
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            DB_HOST: host.docker.internal
            DB_DATABASE: pvmbg
            DB_USERNAME: root
            DB_PASSWORD: toor
            DB_CONNECTION_PMBGI: pgsql
            DB_HOST_PMBGI: 172.16.2.121
            DB_PORT_PMBGI: 5432
            DB_DATABASE_PMBGI: pmbgi
            DB_USERNAME_PMBGI: pmbgi
            DB_PASSWORD_PMBGI: pmbgi
            REDIS_HOST: host.docker.internal
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - intranet
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8083:8000"
            # we need not ssl
            #- "1443:443"
        volumes:
            - ./:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            #- ./nginx/ssl/:/etc/nginx/ssl/
        networks:
            - intranet
networks:
    intranet:
        driver: bridge
